stages:
  - build

image: eclipse-temurin:21-jdk

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/caches
    - .gradle/wrapper

build:
  stage: build
  script:
    - ./gradlew --no-daemon clean build
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - build/libs/*.jar
      - build/publications/**
